# Generated by Django 4.2.7 on 2023-12-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_DOB',
            field=models.IntegerField(default=1982),
        ),
    ]
