# Generated by Django 4.2.7 on 2023-12-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_DOB',
        ),
    ]
